[package]
name = "d7049e_game_project"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1"
ogl33 = { version = "0.2.0", features = ["debug_error_checks"]}
rust-3d = "0.34.0"
kiss3d = "0.34"
nalgebra     = "0.30"
downcast-rs = "1.2.0"

[build-dependencies]


